// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import Link from "next/link";

function About$default(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement("h1", {
                  className: "text-3xl font-bold underline"
                }, "About page"), React.createElement("p", undefined, React.createElement(Link, {
                      href: "/",
                      children: "Home"
                    })));
}

var $$default = About$default;

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
