// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import Link from "next/link";

function Index$default(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement("h1", undefined, "Hello world!"), React.createElement("p", undefined, React.createElement(Link, {
                      href: "about",
                      children: "About"
                    })));
}

var $$default = Index$default;

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
